language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev
install: true
script:
  - g++ -g -std=c++14 *.cpp -o test
  - ./test
